[project]
name = "genai-and-agenticai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=1.6.0",
    "langchain[huggingface,openai]>=1.3.18",
    "pandas-stubs>=3.0.5.260730",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "streamlit>=1.63.0",
]
